default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  sslmode: require


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: student_helpdesk_db
  username: stduent_helpdesk_db_owner
  password: <%= ENV['DATABASE_PASSWORD'] %>
